name = "Pigeon Town"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "A warm, pigeon-inspired Micro.blog theme. Supports short posts, long form articles, photos, books, games, and pigeon pics."
tags = ["blog", "minimal", "microblog", "photos"]
features = ["blog", "photos", "books"]
min_version = "0.91.0"

[author]
  name = ""
  homepage = ""
